// frontend/src/views/Settings.vue
<template>
  <v-container fluid class="settings-page">
    <v-row class="mb-4" align="center">
      <v-col cols="12" class="d-flex flex-wrap align-center justify-space-between gap-2">
        <div class="d-flex align-center gap-2">
          <v-icon icon="mdi-cog" class="mr-1"></v-icon>
          <div>
            <div class="text-h5 font-weight-bold">Bot Settings</div>
            <div class="text-body-2 text-medium-emphasis">Adjust trading, risk, and automation controls</div>
          </div>
        </div>
        <div class="d-flex flex-wrap gap-2 settings-actions">
          <v-btn color="grey" variant="text" @click="refreshSettings" :loading="settingsLoading">Reset to Current</v-btn>
          <v-btn color="primary" variant="flat" @click="persistSettings" :loading="settingsLoading">
            <v-icon start icon="mdi-check"></v-icon>
            {{ botStatus.running ? 'Apply & Restart' : 'Save Settings' }}
          </v-btn>
        </div>
      </v-col>
      <v-col cols="12">
        <v-alert v-if="botStatus.running" type="info" variant="tonal" class="mb-0">
          <v-icon icon="mdi-information" class="mr-2"></v-icon>
          The bot will restart after you save changes.
        </v-alert>
      </v-col>
    </v-row>

    <v-row class="settings-grid" dense>
      <v-col cols="12" lg="6" xl="4">
        <v-card class="setting-card" variant="tonal">
          <v-card-title class="pb-1">Trading Basics</v-card-title>
          <v-card-text class="pt-1">
            <v-row dense>
              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-switch
                    v-model="settings.PAPER_TRADING"
                    label="Paper Trading Mode"
                    color="primary"
                  ></v-switch>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Paper Trading</b><br><br>Simulates buys and sells without real money. Great for testing safely.</span>
                    </v-tooltip>
                    <span>Simulate trades without real orders</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MAX_PRICE"
                    label="Max Coin Price ($)"
                    type="number"
                    step="0.1"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Max Coin Price</b><br><br>Skip coins priced above this level. Lower values focus on cheaper coins.</span>
                    </v-tooltip>
                    <span>Skip coins priced above this</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.POSITION_SIZE"
                    label="Position Size ($)"
                    type="number"
                    step="50"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Position Size</b><br><br>Dollar amount per trade. Total exposure = Position Size x Max Positions.</span>
                    </v-tooltip>
                    <span>Amount to invest per trade</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MAX_POSITIONS"
                    label="Max Positions"
                    type="number"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Max Positions</b><br><br>Limits how many different coins you can hold at once.</span>
                    </v-tooltip>
                    <span>Maximum open positions</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MIN_VOLUME"
                    label="Min 24h Volume ($)"
                    type="number"
                    step="1000"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Minimum 24h Volume</b><br><br>Requires sufficient liquidity to reduce slippage.</span>
                    </v-tooltip>
                    <span>Minimum trading volume required</span>
                  </div>
                </div>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" lg="6" xl="4">
        <v-card class="setting-card" variant="tonal">
          <v-card-title class="pb-1">Entry & Exit Rules</v-card-title>
          <v-card-text class="pt-1">
            <v-row dense>
              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MOMENTUM_THRESHOLD"
                    label="Momentum Threshold (%)"
                    type="number"
                    step="0.1"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Momentum Threshold</b><br><br>Price must rise at least this percent within the window to buy.</span>
                    </v-tooltip>
                    <span>Minimum rise to trigger buy</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MOMENTUM_WINDOW"
                    label="Momentum Window (minutes)"
                    type="number"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Momentum Window</b><br><br>Time range used to measure the price change.</span>
                    </v-tooltip>
                    <span>Time range for momentum</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.PROFIT_TARGET"
                    label="Profit Target (%)"
                    type="number"
                    step="0.1"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Profit Target</b><br><br>Take profit level before either selling or switching to trailing mode.</span>
                    </v-tooltip>
                    <span>Target profit before exit logic</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.STOP_LOSS"
                    label="Stop Loss (%)"
                    type="number"
                    step="0.5"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Stop Loss</b><br><br>Sell when loss hits this percent. Use negative numbers (example: -5).</span>
                    </v-tooltip>
                    <span>Max loss before selling (negative)</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.SCAN_INTERVAL"
                    label="Scan Interval (seconds)"
                    type="number"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Scan Interval</b><br><br>How often the bot scans markets for signals.</span>
                    </v-tooltip>
                    <span>Time between market scans</span>
                  </div>
                </div>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" lg="6" xl="4">
        <v-card class="setting-card" variant="tonal">
          <v-card-title class="pb-1">Entry Filters</v-card-title>
          <v-card-text class="pt-1">
            <v-row dense>
              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-switch
                    v-model="settings.VOLUME_SURGE_FILTER"
                    label="Volume Surge Filter"
                    color="primary"
                  ></v-switch>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Volume Surge</b><br><br>Require above-average volume before entering.</span>
                    </v-tooltip>
                    <span>Require above-average volume</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.VOLUME_SURGE_THRESHOLD"
                    label="Volume Threshold (%)"
                    type="number"
                    step="10"
                    :disabled="!settings.VOLUME_SURGE_FILTER"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Volume Threshold</b><br><br>Percent of average volume required. Example: 150 means 1.5x average.</span>
                    </v-tooltip>
                    <span>Min volume vs average</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-switch
                    v-model="settings.RSI_FILTER"
                    label="RSI Entry Filter"
                    color="primary"
                  ></v-switch>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>RSI Filter</b><br><br>Only enter when RSI is inside the allowed band.</span>
                    </v-tooltip>
                    <span>Only enter within RSI range</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.RSI_MIN"
                    label="RSI Min"
                    type="number"
                    :disabled="!settings.RSI_FILTER"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>RSI Min</b><br><br>Do not enter if RSI is below this value.</span>
                    </v-tooltip>
                    <span>Minimum RSI to enter</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.RSI_MAX"
                    label="RSI Max"
                    type="number"
                    :disabled="!settings.RSI_FILTER"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>RSI Max</b><br><br>Do not enter if RSI is above this value.</span>
                    </v-tooltip>
                    <span>Maximum RSI to enter</span>
                  </div>
                </div>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" lg="6" xl="4">
        <v-card class="setting-card" variant="tonal">
          <v-card-title class="pb-1">Trailing Profit</v-card-title>
          <v-card-text class="pt-1">
            <v-row dense>
              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-switch
                    v-model="settings.ENABLE_TRAILING_PROFIT"
                    label="Enable Trailing"
                    color="primary"
                  ></v-switch>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Enable Trailing</b><br><br>After hitting profit target, trail price instead of selling immediately.</span>
                    </v-tooltip>
                    <span>Let winners ride after target</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.TRAILING_STOP_PERCENT"
                    label="Trailing Stop (%)"
                    type="number"
                    step="0.1"
                    :disabled="!settings.ENABLE_TRAILING_PROFIT"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Trailing Stop</b><br><br>Sell after price falls this percent from the peak while trailing.</span>
                    </v-tooltip>
                    <span>Sell when price drops from peak</span>
                  </div>
                </div>
              </v-col>

              <v-col cols="12" sm="6">
                <div class="setting-field">
                  <v-text-field
                    v-model.number="settings.MIN_MOMENTUM_TO_RIDE"
                    label="Min Momentum to Ride (%)"
                    type="number"
                    step="0.1"
                    :disabled="!settings.ENABLE_TRAILING_PROFIT"
                  ></v-text-field>
                  <div class="setting-hint">
                    <v-tooltip location="top" max-width="360">
                      <template #activator="{ props }">
                        <v-btn v-bind="props" icon variant="text" size="x-small">
                          <v-icon icon="mdi-information-outline" size="small"></v-icon>
                        </v-btn>
                      </template>
                      <span><b>Min Momentum to Ride</b><br><br>Exit trailing early if momentum drops below this level.</span>
                    </v-tooltip>
                    <span>Exit if momentum fades</span>
                  </div>
                </div>
              </v-col>
            </v-row>
          </v-card-text>
        </v-card>
      </v-col>

      <v-col cols="12" lg="6" xl="4">
        <v-card class="setting-card" variant="tonal" color="error">
          <v-card-title class="pb-1">
            <v-icon icon="mdi-alert" class="mr-2"></v-icon>
            Danger Zone
          </v-card-title>
          <v-card-text class="pt-1">
            <div class="mb-3">
              <div class="text-body-2 mb-2">Reset your paper trading portfolio to start fresh with $10,000.</div>
              <v-btn 
                color="error" 
                variant="flat" 
                @click="showResetDialog = true"
                prepend-icon="mdi-delete-sweep"
              >
                Reset Portfolio
              </v-btn>
            </div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Reset Confirmation Dialog -->
    <v-dialog v-model="showResetDialog" max-width="400">
      <v-card>
        <v-card-title class="text-h5">
          <v-icon icon="mdi-alert" color="warning" class="mr-2"></v-icon>
          Reset Portfolio?
        </v-card-title>
        <v-card-text>
          This will clear all positions and trade history, and reset your cash to $10,000. This action cannot be undone.
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="grey" variant="text" @click="showResetDialog = false">Cancel</v-btn>
          <v-btn color="warning" variant="flat" @click="doResetPortfolio" :loading="resetLoading">Reset</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { onMounted, ref } from 'vue'
import { useTrading } from '../composables/useTrading'

const { botStatus, settings, loadSettings, saveSettings, resetPortfolio } = useTrading()

const settingsLoading = ref(false)
const showResetDialog = ref(false)
const resetLoading = ref(false)

const refreshSettings = async () => {
  settingsLoading.value = true
  try {
    await loadSettings()
  } finally {
    settingsLoading.value = false
  }
}

const persistSettings = async () => {
  settingsLoading.value = true
  try {
    await saveSettings()
  } finally {
    settingsLoading.value = false
  }
}

const doResetPortfolio = async () => {
  resetLoading.value = true
  try {
    await resetPortfolio()
    showResetDialog.value = false
  } finally {
    resetLoading.value = false
  }
}

onMounted(() => {
  loadSettings()
})
</script>

<style scoped>
.settings-page {
  max-width: 1400px;
  margin: 0 auto;
  padding-bottom: 24px;
}

.settings-grid {
  row-gap: 16px;
}

.setting-card {
  height: 100%;
}

.setting-field {
  display: flex;
  flex-direction: column;
}

.setting-hint {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-top: -12px;
  padding-left: 8px;
  font-size: 12px;
  color: rgba(var(--v-theme-on-surface), 0.6);
}

.setting-hint .v-btn {
  min-width: 20px;
  width: 20px;
  height: 20px;
}

.settings-actions {
  justify-content: flex-end;
}

@media (max-width: 960px) {
  .settings-actions {
    width: 100%;
    justify-content: flex-start;
  }
}
</style>

// frontend/app/settings/page.tsx
'use client'

import { useTrading } from '@/hooks/useTrading'
import { Card, CardTitle, CardContent } from '@/components/Card'
import Button from '@/components/Button'
import { Download, Upload, RotateCcw } from 'lucide-react'
import { useState, useRef } from 'react'

export default function SettingsPage() {
  const {
    botStatus,
    settings,
    settingsHistory,
    settingsComment,
    setSettingsComment,
    loadSettings,
    saveSettings,
    resetPortfolio,
  } = useTrading()

  const [settingsLoading, setSettingsLoading] = useState(false)
  const [showResetDialog, setShowResetDialog] = useState(false)
  const [snackbar, setSnackbar] = useState('')
  const [localSettings, setLocalSettings] = useState(settings)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleSettingChange = (key: keyof typeof settings, value: any) => {
    setLocalSettings(prev => ({ ...prev, [key]: value }))
  }

  const handleSave = async () => {
    setSettingsLoading(true)
    try {
      // Apply local settings to global settings
      Object.assign(settings, localSettings)
      await saveSettings()
      setSnackbar('Settings saved successfully!')
      setTimeout(() => setSnackbar(''), 3000)
    } catch (error) {
      setSnackbar('Error saving settings')
      setTimeout(() => setSnackbar(''), 3000)
    } finally {
      setSettingsLoading(false)
    }
  }

  const handleExport = () => {
    const payload = {
      settings: localSettings,
      comment: settingsComment,
      exportedAt: new Date().toISOString(),
    }
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `trader-settings-${new Date().toISOString().slice(0, 16).replace(/:/g, '-')}.json`
    link.click()
    URL.revokeObjectURL(url)
  }

  const handleImport = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    try {
      const text = await file.text()
      const imported = JSON.parse(text)
      const importedSettings = imported.settings || imported
      const validKeys = Object.keys(localSettings)
      const filtered: any = {}
      for (const key of validKeys) {
        if (key in importedSettings) filtered[key] = importedSettings[key]
      }
      setLocalSettings(filtered)
      setSettingsComment(imported.comment || '')
      setSnackbar('Settings imported! Click save to apply.')
      setTimeout(() => setSnackbar(''), 3000)
    } catch (error) {
      setSnackbar('Error importing settings')
      setTimeout(() => setSnackbar(''), 3000)
    }
  }

  return (
    <div className="p-4 space-y-3">
      <div className="flex flex-col md:flex-row gap-3 items-start md:items-center justify-between">
        <h1 className="text-2xl font-bold">Bot Settings</h1>
        <div className="flex gap-2 flex-wrap">
          <Button size="small" variant="secondary" onClick={() => fileInputRef.current?.click()}>
            <Upload size={16} /> Import
          </Button>
          <Button size="small" variant="secondary" onClick={handleExport}>
            <Download size={16} /> Export
          </Button>
          <Button size="small" variant="primary" loading={settingsLoading} onClick={handleSave}>
            {botStatus.running ? 'Apply & Restart' : 'Save'}
          </Button>
        </div>
        <input ref={fileInputRef} type="file" accept=".json" onChange={handleImport} hidden />
      </div>

      {/* Settings Groups - Multi-column layout optimized for 2K */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2k:grid-cols-4 gap-3">
        {/* Trading Mode */}
        <Card variant="glass">
          <CardTitle>Trading Mode</CardTitle>
          <CardContent>
            <div>
              <label className="text-xs text-gray-400 block mb-1">Paper Trading</label>
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={localSettings.PAPER_TRADING}
                  onChange={(e) => handleSettingChange('PAPER_TRADING', e.target.checked)}
                  className="w-4 h-4"
                />
                <span className="text-xs text-gray-300">
                  {localSettings.PAPER_TRADING ? 'Simulated trades' : 'Real trades'}
                </span>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Position Sizing */}
        <Card variant="glass">
          <CardTitle>Position Sizing</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Max Price ($)</label>
                <input
                  type="number"
                  step="0.01"
                  value={localSettings.MAX_PRICE}
                  onChange={(e) => handleSettingChange('MAX_PRICE', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Trade under this price</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Position Size ($)</label>
                <input
                  type="number"
                  value={localSettings.POSITION_SIZE}
                  onChange={(e) => handleSettingChange('POSITION_SIZE', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">USD per trade</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Max Positions</label>
                <input
                  type="number"
                  value={localSettings.MAX_POSITIONS}
                  onChange={(e) => handleSettingChange('MAX_POSITIONS', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Max concurrent</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Profit Targets */}
        <Card variant="glass">
          <CardTitle>Profit & Stops</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Profit Target (%)</label>
                <input
                  type="number"
                  step="0.1"
                  value={localSettings.PROFIT_TARGET}
                  onChange={(e) => handleSettingChange('PROFIT_TARGET', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Sell at %</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Stop Loss (%)</label>
                <input
                  type="number"
                  step="0.1"
                  value={localSettings.STOP_LOSS}
                  onChange={(e) => handleSettingChange('STOP_LOSS', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Cut losses</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Trailing Profit</label>
                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={localSettings.ENABLE_TRAILING_PROFIT}
                    onChange={(e) => handleSettingChange('ENABLE_TRAILING_PROFIT', e.target.checked)}
                    className="w-3 h-3"
                  />
                  <span className="text-xs text-gray-300">On</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Momentum & Timing */}
        <Card variant="glass">
          <CardTitle>Momentum & Timing</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Momentum Threshold (%)</label>
                <input
                  type="number"
                  step="0.1"
                  value={localSettings.MOMENTUM_THRESHOLD}
                  onChange={(e) => handleSettingChange('MOMENTUM_THRESHOLD', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Min change</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Momentum Window</label>
                <input
                  type="number"
                  value={localSettings.MOMENTUM_WINDOW}
                  onChange={(e) => handleSettingChange('MOMENTUM_WINDOW', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Minutes</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Scan Interval</label>
                <input
                  type="number"
                  value={localSettings.SCAN_INTERVAL}
                  onChange={(e) => handleSettingChange('SCAN_INTERVAL', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Seconds</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Volume & Filters */}
        <Card variant="glass">
          <CardTitle>Volume & Filters</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Min Volume ($)</label>
                <input
                  type="number"
                  value={localSettings.MIN_VOLUME}
                  onChange={(e) => handleSettingChange('MIN_VOLUME', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">24h vol</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Volume Surge</label>
                <div className="flex items-center gap-2 mb-1">
                  <input
                    type="checkbox"
                    checked={localSettings.VOLUME_SURGE_FILTER}
                    onChange={(e) => handleSettingChange('VOLUME_SURGE_FILTER', e.target.checked)}
                    className="w-3 h-3"
                  />
                  <span className="text-xs text-gray-300">{localSettings.VOLUME_SURGE_FILTER ? 'On' : 'Off'}</span>
                </div>
                <label className="text-xs text-gray-400 block mb-0.5">Threshold (%)</label>
                <input
                  type="number"
                  value={localSettings.VOLUME_SURGE_THRESHOLD}
                  onChange={(e) => handleSettingChange('VOLUME_SURGE_THRESHOLD', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                  disabled={!localSettings.VOLUME_SURGE_FILTER}
                />
                <p className="text-xs text-gray-500 mt-0.5">% of avg</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* RSI Filter */}
        <Card variant="glass">
          <CardTitle>RSI Filter</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div className="flex items-center gap-2 mb-2">
                <input
                  type="checkbox"
                  checked={localSettings.RSI_FILTER}
                  onChange={(e) => handleSettingChange('RSI_FILTER', e.target.checked)}
                  className="w-3 h-3"
                />
                <span className="text-xs font-medium text-gray-300">{localSettings.RSI_FILTER ? 'On' : 'Off'}</span>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">RSI Min</label>
                <input
                  type="number"
                  value={localSettings.RSI_MIN}
                  onChange={(e) => handleSettingChange('RSI_MIN', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                  disabled={!localSettings.RSI_FILTER}
                />
                <p className="text-xs text-gray-500 mt-0.5">Min</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">RSI Max</label>
                <input
                  type="number"
                  value={localSettings.RSI_MAX}
                  onChange={(e) => handleSettingChange('RSI_MAX', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                  disabled={!localSettings.RSI_FILTER}
                />
                <p className="text-xs text-gray-500 mt-0.5">Max</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Trailing Stop */}
        <Card variant="glass">
          <CardTitle>Trailing Stop</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Trailing Stop (%)</label>
                <input
                  type="number"
                  step="0.1"
                  value={localSettings.TRAILING_STOP_PERCENT}
                  onChange={(e) => handleSettingChange('TRAILING_STOP_PERCENT', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                  disabled={!localSettings.ENABLE_TRAILING_PROFIT}
                />
                <p className="text-xs text-gray-500 mt-0.5">Distance %</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Min Momentum (%)</label>
                <input
                  type="number"
                  step="0.1"
                  value={localSettings.MIN_MOMENTUM_TO_RIDE}
                  onChange={(e) => handleSettingChange('MIN_MOMENTUM_TO_RIDE', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                  disabled={!localSettings.ENABLE_TRAILING_PROFIT}
                />
                <p className="text-xs text-gray-500 mt-0.5">Min thresh</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Pos Check (sec)</label>
                <input
                  type="number"
                  value={localSettings.OPEN_POSITION_SCAN_INTERVAL}
                  onChange={(e) => handleSettingChange('OPEN_POSITION_SCAN_INTERVAL', parseInt(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Check interval</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Fees & Taxes */}
        <Card variant="glass">
          <CardTitle>Fees & Taxes</CardTitle>
          <CardContent>
            <div className="space-y-2">
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Maker Fee (%)</label>
                <input
                  type="number"
                  step="0.01"
                  value={localSettings.MAKER_FEE_PERCENT}
                  onChange={(e) => handleSettingChange('MAKER_FEE_PERCENT', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Limit orders</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Taker Fee (%)</label>
                <input
                  type="number"
                  step="0.01"
                  value={localSettings.TAKER_FEE_PERCENT}
                  onChange={(e) => handleSettingChange('TAKER_FEE_PERCENT', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Market orders</p>
              </div>
              <div>
                <label className="text-xs text-gray-400 block mb-0.5">Tax Rate (%)</label>
                <input
                  type="number"
                  step="0.01"
                  value={localSettings.TAX_PERCENT}
                  onChange={(e) => handleSettingChange('TAX_PERCENT', parseFloat(e.target.value) || 0)}
                  className="w-full bg-surface px-2 py-1 rounded border border-gray-700 text-xs"
                />
                <p className="text-xs text-gray-500 mt-0.5">Profits only</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Comments & History - Full width */}
      <Card>
        <CardTitle>Comments & History</CardTitle>
        <CardContent className="space-y-2">
          <textarea
            value={settingsComment}
            onChange={(e) => setSettingsComment(e.target.value)}
            placeholder="Add a comment..."
            className="w-full bg-surface p-1.5 rounded border border-gray-700 text-xs"
            rows={1}
          />
          <div>
            <h4 className="font-semibold mb-1 text-xs">Recent</h4>
            <div className="space-y-0.5 max-h-24 overflow-y-auto">
              {settingsHistory.slice(0, 4).map((entry, i) => (
                <div key={i} className="text-xs bg-surface p-1 rounded">
                  <p className="text-gray-400">{new Date(entry.savedAt).toLocaleString()}</p>
                  <p className="text-gray-500">{entry.comment || 'No comment'}</p>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Danger Zone */}
      <Card variant="tonal" color="error">
        <CardTitle className="text-sm">Danger Zone</CardTitle>
        <CardContent>
          <p className="text-xs text-gray-300 mb-2">Reset portfolio to $10,000</p>
          <Button size="small" variant="error" onClick={() => setShowResetDialog(true)}>
            <RotateCcw size={14} /> Reset
          </Button>
        </CardContent>
      </Card>

      {/* Dialogs */}
      {showResetDialog && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <Card className="p-6 max-w-md">
            <CardTitle>Reset Portfolio?</CardTitle>
            <CardContent className="space-y-4 mt-4">
              <p className="text-sm text-gray-300">This will clear all positions and trade history. This action cannot be undone.</p>
              <div className="flex gap-2">
                <Button variant="secondary" onClick={() => setShowResetDialog(false)} className="flex-1">Cancel</Button>
                <Button variant="error" onClick={async () => {
                  await resetPortfolio()
                  setShowResetDialog(false)
                }} className="flex-1">Reset</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {snackbar && (
        <div className="fixed bottom-4 right-4 bg-primary-600 text-white px-4 py-2 rounded-lg">
          {snackbar}
        </div>
      )}
    </div>
  )
}
